"""initial migration

Revision ID: 368195cb5a14
Revises: 
Create Date: 2026-09-29 11:42:53.095821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368195cb5a14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('fitness_level', sa.String(length=50), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_failed_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('advanced_calorie_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('resting_heart_rate', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True),
    sa.Column('workout_type', sa.String(length=50), nullable=True),
    sa.Column('exercise_name', sa.String(length=100), nullable=True),
    sa.Column('session_duration', sa.Float(), nullable=True),
    sa.Column('sets', sa.Float(), nullable=True),
    sa.Column('reps', sa.Float(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('experience_level', sa.Float(), nullable=True),
    sa.Column('water_intake', sa.Float(), nullable=True),
    sa.Column('workout_frequency', sa.Float(), nullable=True),
    sa.Column('predicted_calories', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('train_split', sa.Float(), nullable=True),
    sa.Column('derived_metrics', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('owner_notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calorie_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('body_temp', sa.Float(), nullable=True),
    sa.Column('predicted_calories', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('train_split', sa.Float(), nullable=True),
    sa.Column('derived_metrics', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('total_squat_reps', sa.Integer(), nullable=True),
    sa.Column('total_pushup_reps', sa.Integer(), nullable=True),
    sa.Column('total_lunge_reps', sa.Integer(), nullable=True),
    sa.Column('total_jumping_jack_reps', sa.Integer(), nullable=True),
    sa.Column('total_high_knee_reps', sa.Integer(), nullable=True),
    sa.Column('total_burpee_reps', sa.Integer(), nullable=True),
    sa.Column('total_plank_seconds', sa.Float(), nullable=True),
    sa.Column('total_situp_reps', sa.Integer(), nullable=True),
    sa.Column('total_leg_raise_reps', sa.Integer(), nullable=True),
    sa.Column('total_bicycle_crunch_reps', sa.Integer(), nullable=True),
    sa.Column('total_reps', sa.Integer(), nullable=True),
    sa.Column('total_active_minutes', sa.Float(), nullable=True),
    sa.Column('avg_form_score', sa.Float(), nullable=True),
    sa.Column('avg_calories_per_session', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('live_workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('user_weight', sa.Float(), nullable=True),
    sa.Column('squat_calories', sa.Float(), nullable=True),
    sa.Column('pushup_calories', sa.Float(), nullable=True),
    sa.Column('lunge_calories', sa.Float(), nullable=True),
    sa.Column('jumping_jack_calories', sa.Float(), nullable=True),
    sa.Column('high_knee_calories', sa.Float(), nullable=True),
    sa.Column('burpee_calories', sa.Float(), nullable=True),
    sa.Column('plank_calories', sa.Float(), nullable=True),
    sa.Column('situp_calories', sa.Float(), nullable=True),
    sa.Column('leg_raise_calories', sa.Float(), nullable=True),
    sa.Column('bicycle_crunch_calories', sa.Float(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('squat_reps', sa.Integer(), nullable=True),
    sa.Column('pushup_reps', sa.Integer(), nullable=True),
    sa.Column('lunge_reps', sa.Integer(), nullable=True),
    sa.Column('jumping_jack_reps', sa.Integer(), nullable=True),
    sa.Column('high_knee_reps', sa.Integer(), nullable=True),
    sa.Column('burpee_reps', sa.Integer(), nullable=True),
    sa.Column('plank_seconds', sa.Float(), nullable=True),
    sa.Column('situp_reps', sa.Integer(), nullable=True),
    sa.Column('leg_raise_reps', sa.Integer(), nullable=True),
    sa.Column('bicycle_crunch_reps', sa.Integer(), nullable=True),
    sa.Column('total_reps', sa.Integer(), nullable=True),
    sa.Column('form_score', sa.Float(), nullable=True),
    sa.Column('consistency', sa.Float(), nullable=True),
    sa.Column('cadence', sa.Float(), nullable=True),
    sa.Column('active_minutes', sa.Float(), nullable=True),
    sa.Column('exercises_done', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('duration_limit', sa.Integer(), nullable=True),
    sa.Column('min_calorie_goal', sa.Integer(), nullable=True),
    sa.Column('max_calorie_goal', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advanced_calorie_predictions_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('main_prediction_data', sa.JSON(), nullable=False),
    sa.Column('ai_insights', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['advanced_calorie_predictions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advanced_calorie_predictions_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advanced_calorie_predictions_explanations_prediction_id'), ['prediction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_advanced_calorie_predictions_explanations_user_id'), ['user_id'], unique=False)

    op.create_table('calorie_predictions_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('main_prediction_data', sa.JSON(), nullable=False),
    sa.Column('ai_insights', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['calorie_predictions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calorie_predictions_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calorie_predictions_explanations_prediction_id'), ['prediction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_calorie_predictions_explanations_user_id'), ['user_id'], unique=False)

    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('form_quality_score', sa.Float(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('context_factors', sa.JSON(), nullable=True),
    sa.Column('exercise_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_workout_sessions_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('live_workout_session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calorie_prediction_explanation_id', sa.Integer(), nullable=True),
    sa.Column('session_data', sa.JSON(), nullable=False),
    sa.Column('ai_suggestions', sa.JSON(), nullable=False),
    sa.Column('summary_points', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calorie_prediction_explanation_id'], ['calorie_predictions_explanations.id'], ),
    sa.ForeignKeyConstraint(['live_workout_session_id'], ['live_workout_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_workout_sessions_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_workout_sessions_suggestions_calorie_prediction_explanation_id'), ['calorie_prediction_explanation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_workout_sessions_suggestions_live_workout_session_id'), ['live_workout_session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_live_workout_sessions_suggestions_user_id'), ['user_id'], unique=False)

    op.create_table('motion_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('landmarks', sa.JSON(), nullable=True),
    sa.Column('joint_angles', sa.JSON(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('predicted_calories', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('shap_values', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('motion_frames')
    with op.batch_alter_table('live_workout_sessions_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_workout_sessions_suggestions_user_id'))
        batch_op.drop_index(batch_op.f('ix_live_workout_sessions_suggestions_live_workout_session_id'))
        batch_op.drop_index(batch_op.f('ix_live_workout_sessions_suggestions_calorie_prediction_explanation_id'))

    op.drop_table('live_workout_sessions_suggestions')
    op.drop_table('workouts')
    with op.batch_alter_table('calorie_predictions_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calorie_predictions_explanations_user_id'))
        batch_op.drop_index(batch_op.f('ix_calorie_predictions_explanations_prediction_id'))

    op.drop_table('calorie_predictions_explanations')
    with op.batch_alter_table('advanced_calorie_predictions_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advanced_calorie_predictions_explanations_user_id'))
        batch_op.drop_index(batch_op.f('ix_advanced_calorie_predictions_explanations_prediction_id'))

    op.drop_table('advanced_calorie_predictions_explanations')
    op.drop_table('rooms')
    op.drop_table('live_workout_sessions')
    op.drop_table('exercise_statistics')
    op.drop_table('calorie_predictions')
    op.drop_table('alerts')
    op.drop_table('advanced_calorie_predictions')
    op.drop_table('users')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
